### ISSUE TITLE
Port to TBC

### ISSUE THREAD

**Issue by Macumbafeh** [Azilroka/LibHealComm-4.0#20]
Hello,

If this addon predict HOT heals, Can you backport it for tbc?

Feel free to join our Addon discord TBC 2.4.3 to speak with our team :
https://discord.gg/5qVu56M

Thanks!

**Comment by Azilroka** [comment]
There should already be a ported version of this for TBC.
If not it should be simple to port forward.

I do not support private servers as I'm part of a large community and work with some Blizzard Developers.

**Comment by Macumbafeh** [comment]
Ok i understand. Thank you anyway
I didn't find an Addon for predict HOT : /
