### ISSUE TITLE
Chat messages "Your are not in a raid group" in burning crusade classic arenas

### ISSUE THREAD

**Issue by michaelnpsp** [Azilroka/LibHealComm-4.0#34]
In the updateDistributionChannel() function the line:
`if( instanceType == "pvp" ) then `
must be replaced with:
`if( instanceType == "pvp"  or instanceType == "arena" ) then`

**Comment by Luckyone961** [comment]
a9f4b8504556ea8f8280cf2c68c200e47d7c1a62
